spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/msrentcar
    driver-class-name: org.postgresql.Driver
    username: rentacar
    password: 200125
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

telegram:
  bot:
    token: 8725670887:AAFRP2zL6t8Mu4-g7Zn2aGiMteGi2vEfyVg
    chat-id: 6662922595
